name = "Hugo Conference"
license = "MIT"
licenselink = "https://github.com/jweslley/hugo-conference/blob/master/LICENSE"
description = "The easiest way to create websites for conference/events"
homepage = "https://github.com/jweslley/hugo-conference/"
tags = ["conference", "responsive", "l10n", "google-analytics"]
features = ["conference", "responsive", "l10n", "google-analytics"]
min_version = "0.21"

[author]
  name = "jweslley"
  homepage = "//jonhnnyweslley.net"

[original]
  name = "conf-boilerplate"
  homepage = "//braziljs.github.io/conf-boilerplate"
  repo = "//github.com/braziljs/conf-boilerplate"
